### ISSUE TITLE
Set default value for Compute Context when adding a new profile

### ISSUE THREAD

**Issue by Becky-Williamson** [sassoftware/vscode-sas-extension#114]
It would be a nice feature to set a default value for the compute context when creating a new profile.  It took me a couple of tries to figure out what exactly we were looking for in that field.  Since SAS Studio defaults to the "SAS Studio compute context", it would be nice if this did as well.

**Comment by scnwwu** [comment]
There **is** a default value, which is "SAS Job Execution compute context". When you create a new profile from UI, it will be in the SAS Compute Context prompt initially. If you simply edit JSON, you can leave this field not set and it will take the default. What's your steps with problem?

**Comment by clangsmith** [comment]
We would need to think a little more about this. Whether we use the Job Execution context or the SAS Studio context by default, neither of those is really meant for Visual Studio Code (since it is truly a separate context). I think the argument could definitely be made that the SAS Studio experience is more similar to VS Code than Job Execution, which lends some weight to using SAS Studio's compute context by default. However, rather than defaulting to any of the existing compute contexts, another option may be to create a new "Visual Studio Code compute context" OOTB in Viya and default to that. That would allow admins to control the environments independently OOTB. (Of course, you can manually create a new dedicated compute context today if you want to control the compute settings used in VS Code separately.)

**Comment by clangsmith** [comment]
Closing as Won't Do. Discussed with the team today and we agreed continuing to use the Job Execution compute context by default is sufficient for now, since users can still change to a different compute context, even a new one that they create in Viya.
