### ISSUE TITLE
add a visual indication whether a connection to a compute server exists or not

### ISSUE THREAD

**Issue by brunomueller** [sassoftware/vscode-sas-extension#119]
Currently there is no visual indication to see whether a connection to the compute server exists or not.
![image](https://user-images.githubusercontent.com/4791387/217460059-99ae77eb-85a2-436e-86a4-5de9fd3d178b.png)

One can hover over the icon and then get the "close connection", but you always get this text independant of whether there is a connection or not

**Comment by dfxvir** [comment]
@brunomueller 
could you resend the screenshot?

**Comment by brunomueller** [comment]
![vs_code_connect_sas](https://user-images.githubusercontent.com/4791387/219389848-e71be412-1442-42db-b543-ea7a57195f07.png)

**Comment by brunomueller** [comment]
![vs_code_connect_sas](https://user-images.githubusercontent.com/4791387/219390516-fd0ce7d7-3192-4bdc-a19d-14a28f51dbb2.png)

The image is somehow not shown, but clicking on the link will show it, at least for me, this works

**Comment by clangsmith** [comment]
I agree, it would be much nicer to correctly reflect the connection state.

Additionally, I feel that having that "Close Current Session" button in the toolbar for every SAS program is not appropriate, since it really applies to the entire SAS extension. I think it would make more sense for the connection state to be next to the SAS profile (or combined with) on the VS Code status bar, since they are closely related. Those 1 or 2 buttons on the status bar should reflect the current profile and the current connection state (connected or disconnected) of that profile. From those 1 or 2 buttons, you should be able to change profiles (which will immediately disconnect the current server session if there is a current session), explicitly make a connection if don't already have a connection, and explicitly disconnect from an existing connection (if already connected).
