### ISSUE TITLE
[Code Editor] Support sections requiring only section start definition for display VSCode Outline panel

### ISSUE THREAD

**Issue by ShuguangSun** [sassoftware/vscode-sas-extension#1211]
**Is your feature request related to a problem? Please describe.**
Currently the outline shows the PROC, DATA step, and REGION block. For long and large code file, it would be helpfult if there is some kind of section.

**Describe the solution you'd like**
In Rstudio, it use `# name ----` for a section of `name`.  If SAS extenstion has some thing like it and show it in outline, it wold be helpful to understand the stucture of code.

Althogh REGION block can do it, but it need an end and not so convenient.

**Comment by snlwih** [comment]
@ShuguangSun, as you mentioned you can do this using region blocks, which also supports sub regions. This is then used for code folding and for display in the VS Code Outline panel. Although I understand that this would be a "nice to have", we have so many feature requests on the list that the contributors at SAS will have to focus on those. Therefore closing.

For others reading this I have included a [pointer to the doc describing the region functionality](https://sassoftware.github.io/vscode-sas-extension/Features/sasCodeEditing?_highlight=region#code-folding-and-code-outline) and a screenshot showing an example. 
![image](https://github.com/user-attachments/assets/701458e7-1842-4a92-917c-be6cbb6ca1c1)

**Comment by snlwih** [comment]
Made a mistake during closing, should have used the "Close as not planned option" from the pulldown menu that is available on to as part of the "Close with comment" button. And once that option has been selected, type the comment and click the "Close with comment" button. Otherwise it will use the default with is "Close as completed".
![image](https://github.com/user-attachments/assets/04a35387-9e96-459b-95ac-60992e4ef40e)

Doing this now. 
@scnwwu , thanks for making me aware of this.
