### ISSUE TITLE
NODE_EXTRA_CA_CERTS doesn't work

### ISSUE THREAD

**Issue by scnwwu** [sassoftware/vscode-sas-extension#220]
To workaround the `unable to verify the first certificate` error on Windows, [NODE_EXTRA_CA_CERTS](https://nodejs.org/api/cli.html#node_extra_ca_certsfile) was provided in our [FAQ](https://github.com/sassoftware/vscode-sas-extension/wiki/FAQ#i-got-unable-to-verify-the-first-certificate-error-when-run).
However it does NOT really work due to https://github.com/electron/electron/issues/10257 (It said fixed but not really, see the latest comments).
We need a way for users to add extra certs.

**Comment by SundareshSankaran** [comment]
Since this is related to the error, may I ask a clarification and a suggestion on the same thread?

1. By root CA certificate in the URL, do you mean the cluster truststore certs or the Viya platform root CA cert, or does it matter?  The documentation link (for latest versions) says "or" in the heading, but not sure what is sufficient (at a minimum) for connecting.  Administrators who typically run the kubectl commands may not wish to provide certs beyond the minimum required.

3. Could you please fix the link for the "Obtain the root CA certificate" in the FAQ to point to the latest version (usually by replacing a part of the URL with default) - for example, this link takes you to the section for 2023.04 (latest current) : [https://go.documentation.sas.com/doc/en/sasadmincdc/**default**/calencryptmotion/n1xdqv1sezyrahn17erzcunxwix9.htm#n0309hwuyq56x2n17mkapfltqau6](https://go.documentation.sas.com/doc/en/sasadmincdc/default/calencryptmotion/n1xdqv1sezyrahn17erzcunxwix9.htm#n0309hwuyq56x2n17mkapfltqau6). (the question of which cert still exists).

**Comment by scnwwu** [comment]
@SundareshSankaran, I'll update the FAQ page once #221 merged.
I'll remove the "Obtain the root CA certificate" step from the FAQ. Instead, let user export the certificate from browser, which is a  much easier way.

**Comment by SundareshSankaran** [comment]
Thank you, @scnwwu

**Comment by SundareshSankaran** [comment]
Hi @scnwwu , please let me know if this requires a new ticket, or can be continued under this closed issue.  A SAS colleague (Brian Kinnebrew) finds that the problem of "unable to verify the first certificate" continues on a Windows machine, even after following instructions as per the extension and the additional options.  He's currently using the NODE_TLS_REJECT_UNAUTHORIZED workaround.  Thanks.
