### ISSUE TITLE
Format SAS code

### ISSUE THREAD

**Issue by djhbs** [sassoftware/vscode-sas-extension#28]
The Syntax Highlighting and Pop-up Syntax are very great and usefull.
I wonder if there is the functinality of formating SAS code like the SAS EG or SAS Studio.

**Comment by clangsmith** [comment]
This functionality does not currently exist for SAS code in the SAS extension for VS Code, however I agree, it would be a nice feature to add. We will track this as a feature request. Currently, if you try to format the document (ex. Shift+Alt+F), you get the following dialog from VS Code ("There is no formatter for 'sas' files installed."):

![image](https://user-images.githubusercontent.com/9735352/201348040-9d4d9600-9b56-48ed-be47-22c3f1cbd2ed.png)

**Comment by clangsmith** [comment]
Please make sure to review the existing implementations/algorithms in SAS Studio and EG to see what we can/should port or re-use. We should not have to start from scratch.

**Comment by annakirkpatrick** [comment]
In as someone with a physical disability, this would be a really useful feature! 

I rely primarily on eye gaze-based input to write code (which is a good deal slower than typing), and I often choose to skip the extra keystrokes required for nice formatting when I'm writing code and rely on automated formatting tools to make my code look presentable. Not having those tools for SAS is really a bummer!

(I can't use SAS Studio because I rely on vim key bindings, available through a VS Code extension, to efficiently navigate and edit code without using a mouse.)
