### ISSUE TITLE
SAS Viya 3.5: Profile with self-signed certificate

### ISSUE THREAD

**Issue by AlexeiNep** [sassoftware/vscode-sas-extension#288]
Hello, 
I try create new profile to SAS Viya 3.5. Our environment working with self-signed certificate.
Is it possible to disable certificate verification?
![image](https://github.com/sassoftware/vscode-sas-extension/assets/59791776/52ad5ff6-3254-40b5-a726-f9cf55fd0090)

Regards,
Alexei

**Comment by scnwwu** [comment]
- There's a VS Code bug https://github.com/microsoft/vscode/issues/181404 that has been fixed in 1.78.2
  If your certificate is trusted in your system, you can update VS Code to 1.78.2

- To bypass certificate check

1. Set environment variable [NODE_TLS_REJECT_UNAUTHORIZED](https://nodejs.org/api/cli.html#node_tls_reject_unauthorizedvalue) to 0.

2. Shut down all VS Code instances and restart to pick up the environment variable. If you're connecting to a remote workspace, please set the environment variable on the remote system and kill all vscode server processes (for example, run `ps -aux | grep vscode-server` on the remote Linux to see the processes).

**Comment by ncstate01** [comment]
I hit this with Viya 4 as well using dev containers.  I added  "NODE_TLS_REJECT_UNAUTHORIZED": "0" to my containerEnv array in the .devcontainer /devcontainer.json file.  Then I rebuilt my container via VSCode and I was able to connect.
