### ISSUE TITLE
SAS Log only appears after all the code has executed.

### ISSUE THREAD

**Issue by JosephDHenry** [sassoftware/vscode-sas-extension#39]
Currently the SAS Log only appears after the code has completed. 
It would be very nice if the log was updated as the program was running.

**Comment by clangsmith** [comment]
Since I didn't see any steps to reproduce in this ticket, I tried to confirm with the following code and it worked great (the log lines appeared in the Output window as the program was running):

`proc optmodel;
  number n init 60;
  set ISET = 1..n;
  number pi = constant('PI');
  var rho{i in ISET} <= 1 >= 0                      /* polar radius */
      init 4*i*(n + 1 - i)/(n+1)**2;
  var theta{i in ISET} >= 0 /* polar angle */
      init pi*i/n;
  con diam{i in ISET, j in i+1 .. n}:
      rho[i]**2 + rho[j]**2 - 2*rho[i]*rho[j]*cos(theta[j] - theta[i])
      <= 1; 
  con increasing{i in 2..n}: theta[i] >= theta[i-1];
  con fix_theta: theta[n] = pi;
  con fix_rho: rho[n] = 0;
  maximize area = 0.5*sum{i in 2..n} rho[i]*rho[i-1]*
      sin(theta[i]-theta[i-1]);
  solve with nlp/tech=as logfreq=10;
  %put &_oroptmodel_;
quit;`
