### ISSUE TITLE
Indentation improvement for SAS code typing

### ISSUE THREAD

**Issue by Zhirong2022** [sassoftware/vscode-sas-extension#522]
**Describe the bug**
This issue comes from PR https://github.com/sassoftware/vscode-sas-extension/pull/451. It needs to do some indentation improvement for SAS code typing in certain scenario.

**Steps to reproduce**
1. Open VSC SAS Extension
2. Type SAS code below
   data a;
3. Type Enter to input
   a=run;
4. Type Enter

**Expected behavior**
It should have indentation in such scenario, since ‘run’ is regarded as a variable. 

**Screenshots**
![image](https://github.com/sassoftware/vscode-sas-extension/assets/121005702/15f77481-e9bf-480c-bd51-3c22f1d96058)

**Environment (please complete the following information):**
Client OS: [e.g. Windows 11]
Extension version: [e.g. v1.3.0]

**Comment by jingjiajie** [comment]
I'd provide some information:
This bug is already known as a CodeZone parsing bug:
`data a;
a=run<DATA_STEP_STMT_OPT_VALUE: 542> ; <GBL_STMT: 500>
`
The <GBL_STMT: 500> is not correct, which caused the outdent, and the correct zone should be <DATA_STEP_STMT_OPT_VALUE: 542>. 
We need to fix CodeZone parsing logics when we have time to prioritize it.
