### ISSUE TITLE
Support SAS content navigation

### ISSUE THREAD

**Issue by scottdover** [sassoftware/vscode-sas-extension#56]
**Is your feature request related to a problem? Please describe.**
At the moment, we're unable to browse SAS Content

**Describe the solution you'd like**
Consumers should be able to browse SAS content

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by scottdover** [comment]
I'm currently thinking we should have:
 - A single view container for SAS
 - A view for SAS Content pane

A rough example of how we might use this can be found here:
![view-container](https://user-images.githubusercontent.com/1058265/207126375-fa377357-5c22-4d30-a673-5bb9c8ea0600.png)

This is pulled from https://code.visualstudio.com/api/ux-guidelines/views . I expect SAS content pane to be a Tree View in this case.

**Comment by mail2fei** [comment]
@boyce-w has done a demo version looks like SAS content navigator, Boyce, is that demo code reusable?

**Comment by scottdover** [comment]
Oh nice. Hopefully some of that can be reused. I've reached out to UX about _how_ this should work and should have a better handle on things then (probably in the New Year at this point since our two UX resources go on PTO Wednesday)

**Comment by clangsmith** [comment]
I assume part of this feature is to support opening and saving content from this location (SAS Content) as well? If so, probably good to spell that out in the solution. For example, would like to be able to...
-Open .sas, .py, .txt (and other text-based file types?) from the SAS Content location, edit in VS Code, then save back to SAS Content.
-Create new files in VS Code and save them to SAS Content.
-Be able to see, open, and edit .sas, .py, .txt files in SAS Studio that were edited and/or created in VS Code.

We should review SAS Studio's Explorer/"SAS Content" pane and SAS Drive's folder tree functionality, since we want to provide a reasonably consistent experience. For example, Drive currently supports Undo, while SAS Studio currently does not, but would like to in future.

**Comment by boyce-w** [comment]
> @boyce-w has done a demo version looks like SAS content navigator, Boyce, is that demo code reusable?

Yes, I developed a prototype. It was able to explore the SAS content within a tree view and open the file in the VS Code. It talks with the folder service. I'll try to integrate into this latest version when I have bandwidth. Thanks.

**Comment by scottdover** [comment]
Hey @boyce-w. If you wanted to push up your code to a branch or a draft PR as you have time, that could be helpful. I'm currently working on setting up an authentication provider (see https://code.visualstudio.com/api/references/vscode-api#AuthenticationProvider) and will take on the content pane after that piece is complete.

**Comment by scottdover** [comment]
> We should review SAS Studio's Explorer/"SAS Content" pane and SAS Drive's folder tree functionality, since we want to provide a reasonably consistent experience. For example, Drive currently supports Undo, while SAS Studio currently does not, but would like to in future.

@clangsmith Would it make sense for sas content to look something like:
![Screenshot 2023-01-04 at 3 09 07 PM](https://user-images.githubusercontent.com/1058265/210640746-11c9d521-57ad-4413-ba10-139a69519bdf.png)=

**Comment by boyce-w** [comment]
VSCode provides 2 approaches to show the remote file content in the editor. 
1. TextDocumentContentProvider - it creates a readonly document from arbitrary sources. Obviously, it's not editable. User could only view the sas code and run.
2. FileSystemProvider - it allows to implement a full file system as a virtual workspace. It's flexible and powerful. It supports create, edit, save, rename, copy, and delete.

It looks like FileSystemProvider is what we need, but as [VS Code documentation](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider) described, it assumes hierarchical paths, e.g. foo:/my/path is a child of foo:/my/ and a parent of foo:/my/path/deeper. But actually the members are not organized like that. For example, if  ItemA is located at Folder1 -> SubFolder2 -> DeepFolder3, the uri of the member ItemA is
/folders/folders/deep-folder3-uri/members/item-a-uri
instead of 
/folder1-uri/sub-folder2-uri/deep-folder3-uri/item-a-uri
 
I'm trying to find out a workaround.

**Comment by scottdover** [comment]
I'm going to defer the `AuthenticationProvider` piece of this to https://github.com/sassoftware/vscode-sas-extension/issues/94, as it'll be a bigger change and is slightly out of scope.

**Comment by boyce-w** [comment]
I tried to combine the TreeDataProvider and FileSystemProvider together to render the folders in a tree view and provide ability to open, edit, and save the sas program file. I created a draft pr and I think we can move on based on it.

**Comment by clangsmith** [comment]
@scottdover sorry for very late reply. Yes, that is roughly what I would expect it to look like (as consistent as reasonably possible), but I'll defer to @skyeaussie for the details.

**Comment by scottdover** [comment]
Hey @clangsmith. Working through this implementation, I'm wondering if we could split this into two "versions." Here's what I'm thinking.

**Version 1**
 - Create: We'll use the type service and provided extension to determine which type to use
 - Edit
 - Rename
 - Delete: For v1, delete will delete the file as it does in SAS Studio/Microsoft 365 (it really deletes the file)

**Version 2**
 - Delete: For v2 (maybe v1), delete will move files to the recycle bin as it does in SAS Drive
 - Drag and Drop functionality: This includes moving files, dropping files to upload, etc

My expectation is that v1 and v2 won't come too far apart. I'm really just trying to split this work so that:
 - we can release _some_ functionality more quickly
 - code review for one piece doesn't become too challenging

Does that sound reasonable, or would we rather just have this all wrapped before releasing anything?

**Comment by clangsmith** [comment]
@scottdover the two step (iterative) approach makes a lot of sense to me and would be my preference as well.
