### ISSUE TITLE
Connection to a Lustre File system to browse in VSCode SAS Extension's Explorer

### ISSUE THREAD

**Issue by alexchouchene** [sassoftware/vscode-sas-extension#649]
**Is your feature request related to a problem? Please describe.**
The VScode explorer allows the browing of our home folders located on our AWS Lustre FsX file system but we haven't found the way to do the same within the explorer of the SAS Extension.

**Describe the solution you'd like**
We'd like to be able to browse an FsX for Lustre file system directly from the VSCode SAS extention.

**Describe alternatives you've considered**
N/A

**Additional context**

**Environment**
SAS version:
Product name:	SAS® Studio (Analyst)
Version:	Long-Term Support 2023.03
Release:	20230518.1684436539151

**Comment by scnwwu** [comment]
Would you provide more details about your use case? Why the VS Code explorer doesn't meet your need?

**Comment by alexchouchene** [comment]
Hi :)
Sure!

Here is what I see in the SAS VScode Explorer:
![image](https://github.com/sassoftware/vscode-sas-extension/assets/101650470/23db9500-96ed-4ce1-bc9f-723c2f3d6635)


Here is what I'd like to be able to see (I am showing now, VSCode, outside of the SAS Extension):
![image](https://github.com/sassoftware/vscode-sas-extension/assets/101650470/22a0782b-0da0-46be-b2eb-b006e48b501d)


I am litterally at the same place but cannot see what's on my Lustre storage.

Does this help please?

Thank you!

**Comment by alexchouchene** [comment]
Would it be possible to call the explorer view from Vscode, whithin the SAS explorer's plugin? So that I can have the same default explorer view without leaving the SAS extention?

**Comment by snlwih** [comment]
Think there is some confusion about the purpose of the Explorer panel inside the SAS Extension. Let me start by explaining what is it and what it isn't (and hopefully not cause even more confusion)

The Explorer panel inside the SAS Extension surfaces items that are known to the SAS session that is currently connected to. Or to be more precise, it surfaces content from the SAS Viya Content Service and that content can used (filename myfile filesvrc ...)  in a SAS Viya 4 Compute Server. So in that respect, it serves a different purpose then the VS Code Explorer panel, which if I'm not mistaken surfaces files/folders directly accessible from the machine where the VSCode client runs. 

As was explained earlier on this thread, when connected to SAS Viya 4 server, you can drag-and-drop files from that explorer into the SAS Explorer panel (when using a profile that uses a SAS Viya 4 server). It will copy the files into the Viya 4 SAS Content server. You can then also drag-and-drop a file from that SAS Content folder into the code editor and it will generate a filename statement. Here is a screenshot that tries to explain this:
![image](https://github.com/sassoftware/vscode-sas-extension/assets/35299890/d69b887a-5eaf-4aa2-b770-0012ce027dbf)

Long term vision is that the Explorer panel inside the SAS Extension would be able to surface the file system associated with the SAS Server that is defined in the current connection profile. And if that SAS Server would have specific types of file systems mounted, this would (hopefully) be transparent to the SAS Server, and therefore be transparent to the Explorer panel inside the SAS extension. This would allow you to drag-and-drop a file inside the SAS code editor and that resulting in filename being added in the SAS code editor that resolves correctly when that SAS code is run on the server defined in the current profile, similar to the screenshot above. But in this case the file lives on the file system, so it would generate a good old standard filename statement without having to use the filesrvc access method. Hope this makes sense.

At the moment the Explorer panel in the SAS Extension is only supported for connections to SAS Viya 4, and on top of that it doesn't surface the file system for the SAS Viya Compute Server.

@alexchouchene , hope the above (very long) explanation was helpful and you kept reading to this point. Btw. if it turns out that your use case is about surfacing the SAS Server file system in SAS Explorer panel when using a connection to SAS Viya 4, then I would recommend to create a dedicated GitHub Issue for that use case and attach the "feature request" label.

**Comment by scnwwu** [comment]
Just to be clear, the drag and drop in my last comment was talking about dragging the "view", not files, shown below.
![dragView](https://github.com/sassoftware/vscode-sas-extension/assets/96556502/47322722-117d-423a-8886-347dbd3c944b)
It won't impact how the folders and files are stored.
As @snlwih explained you can also choose to drag folders and files to SAS Content service. They're different.
There's already a #417 for the SAS server file system.

**Comment by alexchouchene** [comment]
Hi @scnwwu and @snlwih,
Thank you very much for your help, I got all my answers.
Regards,
Alexandre.

**Comment by scnwwu** [comment]
Glad to hear. Closing.
