### ISSUE TITLE
Command 'SAS.addProfile ' not found

### ISSUE THREAD

**Issue by rajahram** [sassoftware/vscode-sas-extension#825]
**Describe the bug**
I have followed the steps as mentioned [here](https://communities.sas.com/t5/SAS-Communities-Library/How-to-use-VS-Code-with-SAS-OnDemand-for-Academics/tac-p/916045). I do not have SAS system installed in my system but I installed SAS Integration Technologies Client for Windows.

**Steps to reproduce**

1. Press Ctrl+Shift+P or F1 to show available commands, and select "SAS: Add New Connection Profile".
2. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/sassoftware/vscode-sas-extension/assets/18627486/9b669aa4-2e5a-4e7a-bb23-9831a75dd270)

**Environment (please complete the following information):**
Client OS: Windows 11
Extension version: 1.7.0
SAS version: SAS Integration Technologies Client for Windows SAS 9.4M8

**Additional context**
VS Code version details
Version: 1.86.1 (user setup)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:20.941Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by JanKwiat** [comment]
I have the same with latest version of VS code and SAS extension
![image](https://github.com/sassoftware/vscode-sas-extension/assets/157806847/cd0953e7-9696-4790-8129-cfe497499acb)

**Comment by radpsz** [comment]
Same for me:
<img width="460" alt="2024-02-15 10_55_34-Visual Studio Code" src="https://github.com/sassoftware/vscode-sas-extension/assets/149955958/853a1b9d-cace-4251-a199-cb2775bf5f59">

**Comment by scottdover** [comment]
Hey everyone. Thank you for bringing our attention to this issue. This will be resolved in v1.7.1, which we plan to release as soon as possible. 

This issue was introduced in v1.7.0 and will impact users who:
 - have no profiles (new users to our extension)
 - have no active profile (an edge case mostly affecting developers)

From a technical perspective, we're working on some upcoming changes to support libraries and tables for IOM/COM connections. One of those changes was to update our library code to be connection agnostic. Previously, this code was tightly-coupled to Viya connections. In updating our code, we failed to account for the fact that _some_ of our users have no active profile. The offending code can be found [here](https://github.com/sassoftware/vscode-sas-extension/blob/21ce708445462b45967ee247c072e7a946ec9442/client/src/components/LibraryNavigator/index.ts#L106-L112).

We've since created a [pull request](https://github.com/sassoftware/vscode-sas-extension/pull/826) to address this issue, where we're making sure we can operate without an active profile.

There are a few changes that should prevent future issues like this from occurring.
 - Our testing guidelines should include testing new code from an empty state (no active profile or profiles specified). Additionally, we should be testing the UIP (update-in-place) path from previous versions of code to the current release.
 - Our unit tests should be covering instances where we're setting up a profile but have no previously created profiles.
 - Our `pull_request_template` should include default tests that _all_ developers will perform when writing new code.

We'll work to make sure these changes are in place soon. 

Thank you again for reaching out, and I apologize for the inconvenience this has caused.
